Update the SLSA provenance predicate to v1
in-toto/attestation pull request #222
Opened 2023-05-12 22:45 UTC by marcelamelara

Also adds the protobuf definition for the v1 predicate (per https://github.com/slsa-framework/slsa/issues/855).

2023-05-19 17:01 UTC, TomHennen requested changes

2023-05-23 15:12 UTC, marcelamelara commented on protos/in_toto_attestation/predicates/provenance/v1/provenance.proto
> +syntax = "proto3";
we certainly can

2023-05-24 17:40 UTC, marcelamelara commented on protos/in_toto_attestation/predicates/provenance/v1/provenance.proto
> +syntax = "proto3";
done!

2023-05-25 14:54 UTC, TomHennen approved these changes
Thanks!

2023-06-02 16:14 UTC, pxp928 approved these changes
LGTM!

2023-06-02 19:59 UTC, merged