Change annotations fields in ResourceDecriptor from objects to values
in-toto/attestation pull request #251
Opened 2023-06-16 16:15 UTC by joshuagl

This change expands support from objects to all JSON values. This allows maximum flexibility for producers and better matches the implicit reading of the spec many, including the SLSA project, had.

Fixes: #242

2023-06-16 16:30 UTC, marcelamelara requested changes
Thanks @joshuagl ! One change that would be help would be to update/add to the examples of the resource descriptor spec to show a more accurate use of value type fields.

2023-06-16 16:39 UTC, joshuagl commented
Whoops, I missed the example. I just pushed 48e03ef to change the existing example. I can try and add one or two more next week if that's desirable?

2023-06-16 17:15 UTC, marcelamelara commented
Thanks! Yeah, _I_ think it would be helpful to have a second example on there that shows different possible values, but I don't think it's crucial. The other thing to consider is how these changes will affect the language bindings/unit tests. But we can resolve that in a separate PR, I figure.

2023-06-26 20:26 UTC, marcelamelara commented
> Can we consider the PR as is? I can file an issue for more examples.

I think so. Thanks!

2023-06-26 20:26 UTC, marcelamelara approved these changes

2023-06-27 18:31 UTC, pxp928 approved these changes
LGTM. +1 with @marcelamelara comment about adding other examples that shows different possible values. Can be in another PR.

2023-06-27 18:31 UTC, merged